import {DEFAULT_ENGINE_CONFIG,normalizeEngineConfig,type EngineConfig} from '../engine/config';
export type ThemeMode='light'|'dark'|'system';export type Language='en'|'fa';
export type TimeControl={id:string;label:string;minutes:number;incrementSeconds:number};
export const TIME_CONTROL_PRESETS:TimeControl[]=[{id:'bullet-1',label:'1+0',minutes:1,incrementSeconds:0},{id:'blitz-3',label:'3+2',minutes:3,incrementSeconds:2},{id:'rapid-5',label:'5+0',minutes:5,incrementSeconds:0},{id:'rapid-10',label:'10+0',minutes:10,incrementSeconds:0}];
export type AppSettings={version:1;theme:ThemeMode;language:Language;sound:boolean;haptics:boolean;boardTheme:{light:string;dark:string;piece:string};engine:EngineConfig;timeControl:TimeControl};
export const DEFAULT_SETTINGS:AppSettings={version:1,theme:'system',language:'fa',sound:true,haptics:true,boardTheme:{light:'#f0d9b5',dark:'#b58863',piece:'#111827'},engine:DEFAULT_ENGINE_CONFIG,timeControl:TIME_CONTROL_PRESETS[2]};
const KEY='yasin-chess-settings-v1';
export function validateSettings(input:unknown):input is AppSettings{if(!input||typeof input!=='object')return false;const x=input as Partial<AppSettings>;return x.version===1&&(x.theme==='light'||x.theme==='dark'||x.theme==='system')&&(x.language==='en'||x.language==='fa')&&typeof x.sound==='boolean'&&typeof x.haptics==='boolean'&&Boolean(x.boardTheme)&&Boolean(x.engine)&&(typeof x.timeControl==='object'||x.timeControl===undefined)}
export function loadSettings():AppSettings{if(typeof localStorage==='undefined')return DEFAULT_SETTINGS;try{const raw=localStorage.getItem(KEY);if(!raw)return DEFAULT_SETTINGS;const x=JSON.parse(raw);return validateSettings(x)?{...DEFAULT_SETTINGS,...x,timeControl:x.timeControl??DEFAULT_SETTINGS.timeControl,engine:normalizeEngineConfig(x.engine)}:DEFAULT_SETTINGS}catch{return DEFAULT_SETTINGS}}
export function saveSettings(patch:Partial<AppSettings>):AppSettings{const next:AppSettings={...loadSettings(),...patch,version:1};if(patch.engine)next.engine=normalizeEngineConfig(patch.engine);if(typeof localStorage!=='undefined')localStorage.setItem(KEY,JSON.stringify(next));return next}
